version: "3"

services:
  api:
    depends_on:
      - db
    image: strapi/strapi
    restart: unless-stopped
    container_name: strapi
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: db_strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: itsastrap!
      DATABASE_SSL: "false"
    ports:
      - 8080:1337
    volumes:
      - /usr/src/api/strapi-app

  db:
    image: mariadb:latest
    container_name: strapi_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: itsastrap!
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
